# -*- coding: utf-8 -*-
"""pdf_to_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DyD2u_NApcrRA-tdANsixuumrQZwcujv

## Steps involved:
1. read pdf file
2. convert each page of pdf file to text file format
3. convert each text file to pandas dataframe
4. combine all pandas dataframe into one
"""

!pip install pypdf PyPDF2
!pip install tabula-py
!pip install pandas

from PyPDF2 import PdfReader
reader = PdfReader("support vector machine algorithim results.pdf") # pdf file path
number_of_pages = len(reader.pages)

print("number_of_pages:", number_of_pages)

import os.path
for i in range(number_of_pages):
  page = reader.pages[i]
  text = page.extract_text()
  print("text:", text)
  filename = 'textdata_'+str(i)+'.txt'
  directory = './pdf_to_txt/'
  file_path = os.path.join(directory, filename)
  if not os.path.isdir(directory):
    os.mkdir(directory)
  file1 = open(file_path, "a")
  file1.writelines(text)

###pdf page 1
import re
import pandas as pd
import itertools
records = []
record = None
for key, subiter in itertools.groupby(open('/content/pdf_to_txt/textdata_0.txt'),
        lambda line: line.startswith("Predict ")): #search string
    if key:
        item_id = next(subiter).split()[1]
        record = {"item_id":item_id}
    else:
        if record:
            record["values"] = [line.strip() for line in subiter]
            records.append(record)

mykey = ['values']
out = [i[x] for i in records for x in mykey]
flat_list = [item for sublist in out for item in sublist]
output = [re.sub('\s+  ',', ',i) for i in flat_list]
df = pd.DataFrame(output, columns=['points'])
df[['Category', 'B']] = df['points'].str.split(',', 1, expand=True)
df[['0', '1']] = df['B'].str.split(',', 1, expand=True)
df = df[['Category', '0', '1']]
print("df:", df)
# df.to_csv("test_1.csv")

##pdf page 2
import re
import pandas as pd
import itertools
records = []
record = None
for key, subiter in itertools.groupby(open('/content/pdf_to_txt/textdata_1.txt'),
        lambda line: line.startswith("RR ")):
    if key:
        item_id = next(subiter).split()[1]
        record = {"item_id":item_id}
    else:
        if record:
            record["values"] = [line.strip() for line in subiter]
            records.append(record)

mykey = ['values']
out = [i[x] for i in records for x in mykey]
flat_list = [item for sublist in out for item in sublist]
output = [re.sub('\s+  ',', ',i) for i in flat_list]
df1 = pd.DataFrame(output, columns=['points'])
df1[['Category', 'B']] = df1['points'].str.split(',', 1, expand=True)
df1[['0', '1']] = df1['B'].str.split(',', 1, expand=True)
df1 = df1[['Category', '0', '1']]
print("df1:", df1)
# df1.to_csv("test_2.csv")

##pdf page 3
import re
import pandas as pd
import itertools
records = []
record = None
for key, subiter in itertools.groupby(open('/content/pdf_to_txt/textdata_2.txt'),
        lambda line: line.startswith("MK(Markedness)  ")):
    if key:
        item_id = next(subiter).split()[1]
        record = {"item_id":item_id}
    else:
        if record:
            record["values"] = [line.strip() for line in subiter]
            records.append(record)

mykey = ['values']
out = [i[x] for i in records for x in mykey]
flat_list = [item for sublist in out for item in sublist]
output = [re.sub('\s+  ',', ',i) for i in flat_list]
df2 = pd.DataFrame(output, columns=['points'])
print("df2:", df2)
df2 = pd.DataFrame(output, columns=['points'])
df2[['Category', 'B']] = df2['points'].str.split(',', 1, expand=True)
df2[['0', '1']] = df2['B'].str.split(',', 1, expand=True)
df2 = df2[['Category', '0', '1']]
print("df2:", df2)
df2.to_csv("test_3.csv")

# combine different pages dataframe into one
final_df = pd.concat([df,df1,df2], ignore_index=True)
print("final_df:", final_df)
final_df.to_csv("support vector machine algorithim results.csv") # name of file to save

